development:
  adapter:   "sqlite3"
  database:  "sudoku_database.sqlite3"
  pool: 10
  timeout: 60000

production:
  adapter:   "sqlite3"
  database:  "home/deploy/sudoku/shared/db/sudoku_database.sqlite3"
